### ISSUE TITLE
Unbinding from non-bound compute throws error ~8

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-compute#8]
From: https://github.com/canjs/canjs/issues/1779

I think:

``` js
var c = can.compute(32);
c.bind('change', can.noop);
c.unbind(); // no error
```

is actually more of a bug.  I think it should either throw an error or actually tear down all event handlers.  calling `.unbind()` is not valid.

**Comment by phillipskevin** [comment]
I think this should work now due to https://github.com/canjs/can-event/releases/tag/v3.7.0. We just need to verify.

**Comment by Macrofig** [comment]
@phillipskevin Just to clarify, calling `unbind()` with `can-event` 3.7 should now tear down all event handlers?

**Comment by phillipskevin** [comment]
Yes.

**Comment by Macrofig** [comment]
Looks like [this function](https://github.com/canjs/can-compute/blob/master/can-compute.js#L49-L54) prevents `can-event` from removing all handlers. `can-event` still gets two arguments that are set to `undefined`.

**Comment by Macrofig** [comment]
Released with [3.3.5](https://github.com/canjs/can-compute/releases/tag/v3.3.5)
